"""
Regenerate every LaTeX table and figure for the paper from the per-sample
prediction files. Run this after the revision matrix has finished (or at any
time - it works off whatever predictions exist).

Pipeline:
  1. scripts/stats.py       -> results/statistics.csv + statistics_table.tex
  2. scripts/breakdowns.py  -> results/breakdowns/*.csv + *.png
  3. this script            -> results/tables/*.tex (grouped paper tables)
  4. LaTeX hygiene check on every .tex under results/: ASCII only,
     `---` never Unicode em-dashes, `\\%` never bare `%` in text.

Usage:
  python scripts/make_paper_tables.py [--skip-recompute]
"""

import argparse
import glob
import os
import re
import subprocess
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import PROJECT_ROOT, RESULTS_DIR  # noqa: E402

TABLES_DIR = os.path.join(RESULTS_DIR, "tables")

# Unicode -> LaTeX-safe replacements applied before the ASCII assertion
UNICODE_REPLACEMENTS = {
    "—": "---",   # em-dash
    "–": "--",    # en-dash
    "±": "$\\pm$",
    "→": "$\\rightarrow$",
    "‘": "`", "’": "'",
    "“": "``", "”": "''",
    " ": " ",
}


def sanitize_latex(text: str) -> str:
    for uni, repl in UNICODE_REPLACEMENTS.items():
        text = text.replace(uni, repl)
    if not text.isascii():
        bad = sorted({c for c in text if not c.isascii()})
        raise ValueError(f"Non-ASCII characters remain in LaTeX output: {bad!r}")
    return text


def check_tex_hygiene(path: str):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.isascii():
        bad = sorted({c for c in text if not c.isascii()})
        raise ValueError(f"{path}: non-ASCII characters {bad!r}")
    # bare % (not \% and not a comment starter at line begin) is a LaTeX
    # comment and silently eats table content
    for lineno, line in enumerate(text.splitlines(), 1):
        stripped = line.lstrip()
        if stripped.startswith("%"):
            continue
        if re.search(r"(?<!\\)%", line):
            raise ValueError(f"{path}:{lineno}: bare % (use \\%): {line.strip()}")
    print(f"  hygiene OK: {path}")


# ---------------------------------------------------------------------------
# Run-name grouping for the paper tables
# ---------------------------------------------------------------------------

def group_of(run_name: str) -> str:
    if "_seed" in run_name:
        return "multi-seed"
    if run_name.endswith("_s2-qlora"):
        return "qlora"
    if re.search(r"_(r\d+|lr[\de.-]+|do[\d.]+|attnonly)$", run_name):
        return "sweep"
    for short in ("fanar", "silma", "qwen"):
        if run_name.startswith(short):
            return "new-models"
    if run_name.endswith("_s2-none"):
        if "_s1-none_" in run_name:
            return "zero-shot"
        return "stage1-only"
    if "_s1-none_" in run_name:
        return "stage2-only"
    return "two-stage"


GROUP_ORDER = ["zero-shot", "stage2-only", "two-stage", "stage1-only",
               "sweep", "qlora", "multi-seed", "new-models"]
GROUP_TITLES = {
    "zero-shot": "Zero-shot baselines",
    "stage2-only": "Stage 2 only",
    "two-stage": "Two-stage (Stage 1 + Stage 2)",
    "stage1-only": "Stage 1 only (forgetting test)",
    "sweep": "LoRA hyperparameter sweep",
    "qlora": "QLoRA",
    "multi-seed": "Multi-seed reruns",
    "new-models": "New base models",
}


def _pct(x: float) -> str:
    return f"{100 * float(x):.2f}"


def grouped_results_table(config_df: pd.DataFrame) -> str:
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py --- do not edit by hand.",
        "% Requires \\usepackage{booktabs}.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Complete results on the cleaned MedAraBench test set:",
        "accuracy and Macro F1 (\\%) with 95\\% bootstrap confidence intervals",
        "(10{,}000 resamples, seed 42).}",
        "\\label{tab:full-results}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Configuration & Accuracy (\\%) & Macro F1 (\\%) \\\\",
    ]
    df = config_df.copy()
    df["group"] = df["run_name"].map(group_of)
    for group in GROUP_ORDER:
        rows = df[df["group"] == group].sort_values("run_name")
        if rows.empty:
            continue
        lines.append("\\midrule")
        lines.append(f"\\multicolumn{{3}}{{l}}{{\\textit{{{GROUP_TITLES[group]}}}}} \\\\")
        for _, r in rows.iterrows():
            name = r["run_name"].replace("_", "\\_")
            acc = (f"{_pct(r['accuracy'])} "
                   f"[{_pct(r['acc_ci_lo'])}, {_pct(r['acc_ci_hi'])}]")
            f1 = (f"{_pct(r['macro_f1'])} "
                  f"[{_pct(r['f1_ci_lo'])}, {_pct(r['f1_ci_hi'])}]")
            lines.append(f"{name} & {acc} & {f1} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return sanitize_latex("\n".join(lines))


def stage1_perplexity_table() -> str | None:
    csv_path = os.path.join(RESULTS_DIR, "stage1_perplexity.csv")
    if not os.path.isfile(csv_path):
        return None
    df = pd.read_csv(csv_path)
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py --- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{AraMed validation perplexity before and after Stage 1",
        "domain adaptation.}",
        "\\label{tab:stage1-ppl}",
        "\\begin{tabular}{llcc}",
        "\\toprule",
        "Model & Stage 1 & PPL before & PPL after \\\\",
        "\\midrule",
    ]
    for _, r in df.iterrows():
        model = str(r["model"]).replace("_", "\\_")
        lines.append(f"{model} & {r['stage1_method']} & "
                     f"{r['ppl_before']:.2f} & {r['ppl_after']:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return sanitize_latex("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-recompute", action="store_true",
                        help="Reuse results/statistics.csv instead of re-running "
                             "stats.py and breakdowns.py.")
    args = parser.parse_args()

    if not args.skip_recompute:
        for script in ("stats.py", "breakdowns.py"):
            print(f">>> {script}")
            rc = subprocess.run(
                [sys.executable, os.path.join(PROJECT_ROOT, "scripts", script)],
                cwd=PROJECT_ROOT).returncode
            if rc != 0:
                print(f"ERROR: {script} failed (exit {rc}); aborting.")
                sys.exit(rc)

    stats_csv = os.path.join(RESULTS_DIR, "statistics.csv")
    if not os.path.isfile(stats_csv):
        print(f"Missing {stats_csv}; run scripts/stats.py first.")
        sys.exit(1)

    all_rows = pd.read_csv(stats_csv)
    config_df = all_rows[all_rows["kind"] == "config"]

    os.makedirs(TABLES_DIR, exist_ok=True)

    main_tex = os.path.join(TABLES_DIR, "full_results.tex")
    with open(main_tex, "w", encoding="ascii") as f:
        f.write(grouped_results_table(config_df))
    print(f"Wrote {main_tex}")

    ppl_table = stage1_perplexity_table()
    if ppl_table:
        ppl_tex = os.path.join(TABLES_DIR, "stage1_perplexity.tex")
        with open(ppl_tex, "w", encoding="ascii") as f:
            f.write(ppl_table)
        print(f"Wrote {ppl_tex}")
    else:
        print("stage1_perplexity.csv not found - skipping perplexity table "
              "(run scripts/eval_stage1_checkpoints.py --perplexity).")

    # Final hygiene pass over every LaTeX file we ship
    print("\nLaTeX hygiene check:")
    for tex in sorted(glob.glob(os.path.join(RESULTS_DIR, "**", "*.tex"),
                                recursive=True)):
        check_tex_hygiene(tex)

    print(f"\nAll paper tables regenerated under {TABLES_DIR}, "
          f"figures under {os.path.join(RESULTS_DIR, 'breakdowns')}.")


if __name__ == "__main__":
    main()
